spring:
  datasource:
    url: jdbc:h2:mem:test;
    driver-class-name: org.h2.Driver
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  h2:
    console:
      enabled: true
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
jwt:
  secret: '4433rjkl2241@!#23l32j14l3kj12l5j14kl2'
  expiration: 86400000  # Token expiration time in milliseconds (e.g., 24 hours)

